✨ Fix MaPharma time
CovidTrackerFr/vitemadose-ios pull request #103
Opened 2021-05-08 16:23 UTC by NathanFallet

Fix #102 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/30439790/117545974-68e5c080-b028-11eb-9495-bc59f9ecf88a.png">

In the case of MaPharma.fr, the date is timezoned without timezone specified. So to fix this, I got the difference between Paris time and UTC/GTM time, to add it at the end of the timezoned date. (so it add `+02:00` or `+01:00` depending on summer or winter time)

Note: my first idea was to remove the `T` to parse it as a local date, but it would work only if user is in correct timezone.

2021-05-08 21:04 UTC, PlugNPush approved these changes

2021-06-05 17:11 UTC, NathanFallet commented
@victor-sarda This fix is waiting to be merged for a month, and is quite important. It would take only two minutes to review it and merge it.

2021-12-29 22:20 UTC, pylapp requested changes

2021-12-29 22:20 UTC, pylapp commented on ViteMaDose/Helpers/Extensions/String+Commons.swift
>      /// - Returns: optional `Date`
Returns optional of String, not Date

2021-12-29 22:20 UTC, pylapp commented on ViteMaDose/Helpers/Extensions/String+Commons.swift
>      /// - Parameter region: custom option `Region`
Missing details for _style_ parameter

2021-12-30 13:39 UTC, pylapp approved these changes

2021-12-30 13:39 UTC, merged