WIP: [#108] Voice Over labels for A11Y improvements
CovidTrackerFr/vitemadose-ios pull request #109
Opened 2021-05-14 10:30 UTC by pylapp

_This is a work in progress pull request_

2021-05-14 15:11 UTC, pylapp commented
@victor-sarda Feel free to contact me for any details and review. These small changes will be helpful for disabled users :)

2021-05-17 13:29 UTC, pylapp commented
@rozierguillaume Any news to review and accept this pull request?

2021-05-17 13:31 UTC, pylapp commented
The merge request for issue #108 is ready for review 👍

2021-05-17 13:33 UTC, victor-sarda commented
> @rozierguillaume Any news to review and accept this pull request?

Apologies for the delay, I was having a small break last week.
Thanks for those accessibility PRs, they're really appreciated, I'll review them this evening :)

2021-05-17 13:46 UTC, pylapp commented
@victor-sarda Sounds great! I am available by email (or maybe by other mediums) if needed!

Cheers

2021-05-17 14:11 UTC, victor-sarda requested changes
I'm sorry I didn't mean to add that many comment 😄 

Most of them are suggestions, you can maybe ignore some if you feel like they're irrelevant 👍 
If you have any question please shout or feel free to join our [Mattermost](https://mattermost.covidtracker.fr/)!

Thanks for the pull request, I really wanted to work on accessibly but couldn't due to time constraints

2021-05-17 14:11 UTC, victor-sarda commented on ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
> +"a11y.voiceover.details.vaccine" = "Vaccin de modèle %@";
```suggestion
"a11y.voiceover.details.vaccine" = "Vaccin de type %@";
```
Maybe?

2021-05-17 14:11 UTC, victor-sarda commented on ViteMaDose/Resources/Localization/fr.lproj/Localizable.strings
> +"a11y.voiceover.locations.see_places" = "Voir les lieux dans le département de %@";
```suggestion
"a11y.voiceover.locations.see_places" = "Voir les lieux pour %@";
```
It's not always a department, happy to use something else if you have a better suggestion though :)

2021-05-18 07:44 UTC, pylapp commented on ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
> +        }
Could be nice however I am not sure this evolution on your backend is mandatory, I fear it will impact other frontends.

2021-05-18 07:52 UTC, pylapp commented
@victor-sarda Seems good now 👍

2021-05-18 17:26 UTC, victor-sarda commented on ViteMaDose/Views/Home/Cells/HomeStatsCell.swift
> +        }
Sorry I meant we already have this value in that app from the backend :)
Anyways I'll merge and we can fix later no worries!

2021-05-18 17:27 UTC, victor-sarda approved these changes
Amazing, thank you 🙏

2021-05-18 17:27 UTC, merged