[#113] Third party components list
CovidTrackerFr/vitemadose-ios pull request #114
Opened 2021-05-17 15:12 UTC by pylapp

To be more compliant with FLOSS principles, and also thanks developers of third-party components used in this project, the list of such components can be made in the app level and the repository level.

- [ ] Add a folder "licenses" listing licenses of components used in the project
- [ ] Add in Settings.bundle of the app a generated lit of components in use

2021-05-17 15:12 UTC, pylapp commented
@victor-sarda @rozierguillaume Merge request related to issue #113 is ready 👍 

Available for review!

2021-05-18 08:15 UTC, pylapp commented
@victor-sarda I reset the Settings.bundle and add the entry of the tool used to build the list of licenses.
Feel free to read this small contribution :)

2021-05-20 07:54 UTC, pylapp commented
@victor-sarda From my point of view, no particular issue with this pull request.
Only a Settings.bundle is created, and it makes the app more compliant with FLOSS guidelines :)

2021-05-20 07:56 UTC, pylapp commented
@victor-sarda About the merge request conflict, how do you want to resolve it? The _pbxproj_ is modified on my side because I created a settings bundle.
Do you want I update it on my side or should I let you update it with your evolutions? .pbxproj files are such a chore to fix when there are conflicts :(

2021-05-20 10:12 UTC, pylapp commented
@victor-sarda Merge request ready again, fixed successfully conflict on pbxproj

2021-05-20 13:22 UTC, victor-sarda commented
> @victor-sarda Merge request ready again, fixed successfully conflict on pbxproj 👍

@pylapp any chance you can provide screenshots? Thanks!

2021-05-20 14:02 UTC, pylapp commented
For sure! You can find below three levels.
First, the app setting screen with the entry of the licenses list, and also a copyright (I thought it might be nice).
Then, the list of dependencies the tool has found directly and by transitions.
Finally, a sample of the result for a component.

In a nutshell: simple, clear, efficient 😄 

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/7559007/118991692-3d49cb00-b984-11eb-8ecb-123d3989f897.PNG" height="300"/>
</td>
<td>
<img src="https://user-images.githubusercontent.com/7559007/118991706-3f138e80-b984-11eb-918b-5ca71b3d5d73.PNG" height="300"/>
</td>
<td>
<img src="https://user-images.githubusercontent.com/7559007/118991711-3fac2500-b984-11eb-95be-4a77511f2e7a.PNG" height="300"/>
</td>
</tr>
</table>

2021-05-20 16:35 UTC, victor-sarda requested changes
Nice one!
I just need you to revert the bundle id/signing in the `pbxproj` file 👍

2021-05-20 16:35 UTC, victor-sarda commented on ViteMaDose.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = pylapp.app.vitemadose;
Can you revert those changes please?

2021-05-25 16:48 UTC, pylapp commented
@victor-sarda That's done. Maybe you should update this file with your team however.

2021-05-29 20:36 UTC, victor-sarda approved these changes

2021-05-29 20:36 UTC, merged