Credits
CovidTrackerFr/vitemadose-ios pull request #122
Opened 2021-05-22 11:48 UTC by NathanFallet

## Description
I'm adding a view to show contributors, based on the backend contributors endpoint

## Related issue
Fixes #37 

## What I tested
I made a `presentCreditViewController()` method in the `HomeViewController`. I called this method to test the view controller, but did not commit this call (to avoid to shown the view when the app opens). So the method is still here, but never called for now, and will be moved to the settings controller when done. (so settings PR will depend on this PR)

## Regression risks
N/A

## Screenshots
_If applicable, add screenshots to help explain the fix. Otherwise please remove this section_
|Before|After|
|-| ![36045A3B-7D95-46A8-A707-97146A77A3D1-9891-000006EB55F5A69D](https://user-images.githubusercontent.com/30439790/119225369-a146cd80-bb03-11eb-90dc-e35444cc95aa.png) |
| | |

## Checklist
- [x] I have installed SwiftLint and made sure code formatting is correct
- [x] I have performed a self-review of my own code
- [x] I tested my changes on real device
- [x] My changes generate no new warnings
- [x] I have commented my code in hard-to-understand areas
- [x] Any dependent changes have been merged into **develop**
- [x] I have checked there aren't other open [Pull Requests](https://github.com/CovidTrackerFr/vitemadose-ios/pulls) for the same update/change

2021-12-30 17:40 UTC, pylapp commented
I tested your _credits_ branch, here are some comments for the feature :)

## About the contributors
1. [] For some contributors, we have a pseudonym of the fulll name, some details about contrebutions or not, and an avatar or not. Is it expected?
2. [] How are sorted the contributors? Maybe be should sort them by alphabetic order and by platforms
3. [] For **Paul Jannot**, an error occurred with it hyperlink. The hyperlink _pauljeannot.github.io_ does not work anymore.
4. [] Same thing for **CorentiOS** with its hyperlink _corentinmedina.fr_
5. [] Same thing for **Alexandre GUY** with its hyperlink _www.agraphik.fr_
6. [] Same thing for **Guillaume Rozier** with its hyperlink _guillaumerozier.fr_

## About the UI
1. [] We cannot see easily if we have a clickable cell because an hyperlink is defined, or not.
Maybe we should add in the contributor cell an image button (containing an SF Symbol) which will redirect the user to the hyperlink target on tap

## About a11y
1. [] We may setup a trick for vocalization of "ios" ; maybe convert the word to "iOS" or change the accessible label
2. [] Accessible fonts are not used in this view ; if we use bigger text sizes in device settings, the text size are not changed

## Miscellaneous
1. [] Need to rebase your branch from _develop_ :)

2021-12-30 18:56 UTC, pylapp requested changes

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Cells/CreditCell.swift
> +        static let labelMainFont: UIFont = .rounded(ofSize: 18, weight: .bold)
Should be replaced by:
```swift
        static let labelMainFont: UIFont = UIFont.accessibleCalloutBold
```

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Cells/CreditCell.swift
> +        static let labelSecondFont: UIFont = .rounded(ofSize: 15, weight: .regular)
Should be replace by:

```swift
static let labelSecondFont: UIFont = UIFont.accessibleSubheadMedium
```

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/CreditViewController.swift
> +        // Case of user
Relevant comment? Not sure :)

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Header/CreditHeaderView.swift
> +        static let searchBarFont = UIFont.rounded(ofSize: 16, weight: .medium)
Unused, should be removed

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Header/CreditHeaderView.swift
> +        static let searchBarViewCornerRadius: CGFloat = 10.0
Unused, should be removed

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Header/CreditHeaderView.swift
> +        static let titleFont = UIFont.rounded(ofSize: 24, weight: .bold)
Replace by:

```swift
static let titleFont = UIFont.accessibleTitle2Bold
static let descriptionFont = UIFont.accessibleCalloutMedium
```

2021-12-30 18:56 UTC, pylapp commented on ViteMaDose/Views/Credits/Header/CreditSectionView.swift
> +//  CreditSectionView.swift
Are you sure _CreditSectionView_ is used? I don't think so ; these objects should be deleted.

2021-12-30 18:57 UTC, pylapp commented
@NathanFallet Almost done! The main things to review are about the accessibility (not managed yet in your feature), and also the ordering of the contributors. A bit of dead code too.

2021-12-31 13:43 UTC, NathanFallet commented
> For some contributors, we have a pseudonym of the fulll name, some details about contributions or not, and an avatar or not. Is it expected?
Yes. The data is returned by the API at `https://vitemadose.gitlab.io/vitemadose/contributors_all.json`, so we have no control about it in the app, and for some of them not all data is filled.

> For Paul Jannot, an error occurred with it hyperlink. The hyperlink pauljeannot.github.io does not work anymore.
> Same thing for CorentiOS with its hyperlink corentinmedina.fr
> Same thing for Alexandre GUY with its hyperlink www.agraphik.fr
> Same thing for Guillaume Rozier with its hyperlink guillaumerozier.fr
As the data is returned by the API, they need to correct the link where it was fetched from. (I think it was taken from GitHub API, so they need to fix the link in their GitHub profile)

> Need to rebase your branch from develop :)
I started the process, it would take too long to do it, with all the changes since the original branch.

> About KingFisher, register this library in the project (licenses folder) and the app (LicenseInfo.plist)
I let you work on that, you seemed motivated to, and know how to.

2021-12-31 18:11 UTC, pylapp commented
@NathanFallet I don't have completed this review and refactoring yet, but it's ongoing.
I hope to complete it this night or tomorrow.

I shared to mates the issue about not working hyperlink and doublons in the contributors JSON file.

Here are the things I will do a soon as possible:
- [ ] Improve VoiceOver vocalization (hint for _ios_, hint for hyperlink icons)
- [ ] Improve UI if too big text size in use
- [ ] Do the rebase from _deveelop_ to keep git history clean
- [ ] Add _KingFisher_ in the project (details in app settings, licence in project)

I keep you in touch !

2022-01-01 17:48 UTC, pylapp approved these changes
Great!

2022-01-01 17:49 UTC, merged