[#47] Settings screen
CovidTrackerFr/vitemadose-ios pull request #123
Opened 2021-05-26 15:12 UTC by pylapp

## Description
_A clear and concise description of what the PR is about_

## Changes
- _A summary of your changes_

## Related issue
_**Please make sure an issue exists before creating a new PR**_

_Link to the [Github issue](https://github.com/CovidTrackerFr/vitemadose-ios/issues)_

## What I tested
_Explain what & how you tested your changes_

## Regression risks
- _List any regression risk if applicable_

## Screenshots
_If applicable, add screenshots to help explain the fix. Otherwise please remove this section_
|Before|After|
|-|-|
| | |

## Checklist
- [ ] I have installed SwiftLint and made sure code formatting is correct
- [ ] I have performed a self-review of my own code
- [ ] I tested my changes on real device
- [ ] My changes generate no new warnings
- [ ] I have commented my code in hard-to-understand areas
- [ ] Any dependent changes have been merged into **develop**
- [ ] I have checked there aren't other open [Pull Requests](https://github.com/CovidTrackerFr/vitemadose-ios/pulls) for the same update/change

2021-05-26 15:28 UTC, pylapp commented
@victor-sarda This merge request for issue #47 is ready for review 👍

2021-05-26 15:44 UTC, NathanFallet requested changes
Seems good, except some unwanted changes in Xcode settings (see review comments) + maybe about analytics (saw your comments in code but don't know if needed or not, see this with @victor-sarda)

2021-05-26 15:44 UTC, NathanFallet commented on ViteMaDose.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Please remove that change from the PR (it should not be committed)

2021-05-26 15:44 UTC, NathanFallet commented on ViteMaDose.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Same here

2021-05-26 15:53 UTC, pylapp commented on ViteMaDose.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Now fixed 😄

2021-05-26 15:54 UTC, pylapp commented
@NathanFallet About analytics I let @victor-sarda provide details, or add them later if needed 👍

2021-05-26 16:33 UTC, NathanFallet approved these changes

2021-05-31 08:46 UTC, pylapp commented
@NathanFallet @victor-sarda I updated the feature branch, feel free to bring your reviews so that we can just after the merge integrate the work of Nathan 👍

2021-06-03 08:16 UTC, pylapp commented
@NathanFallet @victor-sarda Any way to make this request be merged?
Do you need some help?

Cheers 😄

2021-06-03 08:24 UTC, victor-sarda commented
> @NathanFallet @victor-sarda Any way to make this request be merged?
> Do you need some help?
> 
> Cheers 😄

Sorry, again I have almost no time to review/work on the app right now. I'm not 100% sold on this to be honest. Does it add a real value to the app? It's mainly external links, not really settings. Maybe we should discuss what we want to do for a settings screen. Some accessibility settings for instance? Or options like enable/disable dark mode? 
Feel free to join our Mattermost if you want to discuss about it :)

2021-06-03 08:35 UTC, pylapp commented
Indeed I may join your Mattermot team.

In a nutshell, I don't think it is a good idea to override some system settings like light/dark mode or define accessibilty settings, the system does.
In the user story #47 there were only just ideas I tried to implement. Having specific items about social network, source code and contributors may be quite cool.
Maybe should we name it "about" and not "settings" 😃

2021-11-28 11:33 UTC, NathanFallet approved these changes

2021-11-28 13:21 UTC, victor-sarda approved these changes
Nice one!

2021-11-28 13:21 UTC, merged