WIP - Added Valwin logo
CovidTrackerFr/vitemadose-ios pull request #149
Opened 2021-12-02 00:00 UTC by CorentiOS

## Description

Adding Valwin logo

## Changes / Definition of done

- [x] Added logo in footer
- [ ] Check logo size in search section

## Related issue

_Link to the [Github issue](https://github.com/CovidTrackerFr/vitemadose-ios/issues/146)_

## What I tested

- Footer View

## Regression risks

_To be defined_

## Screenshots

_To be defined_

|Before|After|
|-|-|
| | |

## Checklist
- [ ] I have installed SwiftLint and made sure code formatting is correct
- [ ] I have performed a self-review of my own code
- [ ] I tested my changes on real device
- [ ] My changes generate no new warnings
- [ ] I have commented my code in hard-to-understand areas
- [ ] Any dependent changes have been merged into **develop**
- [ ] I have checked there aren't other open [Pull Requests](https://github.com/CovidTrackerFr/vitemadose-ios/pulls) for the same update/change

2021-12-02 00:02 UTC, CorentiOS commented on ViteMaDose/Views/Home/Footer/HomePartnersFooterView.xib
> +                                <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="bimedoc" t
@victor-sarda le logo s'affiche suite à cette modification

2021-12-03 17:05 UTC, pylapp requested changes
- Saut de ligne à ajouter pour la clarté du code
- Ajouter le logo Bimedoc

2021-12-03 17:08 UTC, pylapp commented
@CorentiOS Je pense qu'il manque un élément dans ta pull request.
J'ai cloné ton dépôt, compilé et lancé le code de la branche associée à ta pull request.
J'ai bien d'affiché le logo _Valwin_ dans le footer, mais je n'ai rien concernant _Bimedoc_.
J'aurais tendance à dire que tu n'as pas commité une modification d'un fichier Xcode, type _pbxproj_.

Est-ce voulu ? :-)

![IMG_9534](https://user-images.githubusercontent.com/7559007/144643555-5043252f-d759-4659-9cee-34c15f92e589.jpg)

2021-12-06 10:15 UTC, pylapp approved these changes
Fine!

2021-12-06 10:17 UTC, pylapp commented
@CorentiOS I will merge your pull request _asap_, just need to say with @victor-sarda if the strategy appleid in the project is squash or rebase :)

2021-12-06 21:54 UTC, merged