💬 Dedicated localization file + french language fixes.
CovidTrackerFr/vitemadose-ios pull request #56
Opened 2021-04-22 01:18 UTC by PlugNCS

Fix #42 & Fix #43

Warning: for production, this commit requires the merge of the PR #55 (anytime), and then make sure English is removed (or translated) in the project.

2021-04-22 07:34 UTC, NathanFallet requested changes
Duplicate: The String extension already exists, please delete the extension you added (String+Commons.swift)

2021-04-22 07:43 UTC, PlugNPush commented
> Duplicate: The String extension already exists, please delete the extension you added (String+Commons.swift)

Objection your honor: it was not in the Xcode project, I looked for it for about 10 minutes scanning each file individually looking for the String Extension. 😅

2021-04-22 07:50 UTC, NathanFallet commented
Now the question, as I mentioned in #42, where is the constant enumeration struct?
Let's see if @victor-sarda is okay to merge without it, or if he requests changes.

2021-04-22 07:55 UTC, NathanFallet submitted a review, later dismissed

2021-04-22 07:59 UTC, victor-sarda commented
Since the issue was assigned to me, I started working on it locally. I'm happy to approve after some changes in the String keys. I'll let you know 👍 
@NathanFallet an enum would be nice indeed! If it's too much work we can merge without and add it in another PR 😊

2021-04-22 08:04 UTC, PlugNPush commented
Woi (working on it)

2021-04-22 12:47 UTC, NathanFallet requested changes
Some constant can be replaced by `LocalizedString.id`.

2021-04-22 12:47 UTC, NathanFallet commented on ViteMaDose/Views/CountySelection/Header/CountySelectionHeaderView.swift
> +        static let highlightedText = LocalizedString.area
Useless constant, you can use `LocalizedString.select_your_area` and `LocalizedString.area` directly instead of `titleText` and `highlightedText`.

2021-04-22 12:47 UTC, NathanFallet commented on ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
> +        let titleSecondHighlightedText = LocalizedString.quickly
Same here

2021-04-22 12:47 UTC, NathanFallet commented on ViteMaDose/Views/Home/Cells/HomeTitleCell.swift
> +        let titleText = LocalizedString.last_stats
Same here

2021-04-22 12:47 UTC, NathanFallet commented on ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
> +        static let titleText = LocalizedString.find_appointment_with
Here too

2021-04-22 12:49 UTC, PlugNPush commented on ViteMaDose/Views/Home/Footer/HomePartnersFooterView.swift
> +        static let titleText = LocalizedString.find_appointment_with
Got it!

2021-04-22 13:08 UTC, NathanFallet submitted a review, later dismissed

2021-04-22 13:41 UTC, PlugNPush commented
This PR should now be safe for production :)

2021-04-23 15:55 UTC, PlugNPush commented
Merge WIP

2021-04-23 22:10 UTC, PlugNPush commented
@NathanFallet @victor-sarda Ready for a new review :)

2021-04-23 23:14 UTC, PlugNPush commented
DO NOT ACCEPT THE PR, SWIFTLINT DOES NOT APPROVE IT.

2021-04-23 23:52 UTC, PlugNPush commented
Should now be OK for production, due to the amount of code changed please review carefully. It is SwiftLint compliant and seems to run well in the simulator. Builds with no error (except the pre-existing deprecation warning).

2021-04-24 00:19 UTC, PlugNPush commented
Since this PR got quite messy, should I close it and open a new one with a single all-in-one commit in it?

2021-04-24 00:22 UTC, victor-sarda commented
> Since this PR got quite messy, should I close it and open a new one with a single all-in-one commit in it?

Can you close it and push a branch to the project with your changes please? You can do one single commit and I'll pick your stuff in my branch and open a PR on my side with clean commits 👍

2021-04-24 00:24 UTC, PlugNPush commented
Cleaning things up!

2021-04-24 00:24 UTC, closed without merging